[package]
name = "rustdbus"
version = "0.1.0"
authors = ["Andy Tomaszewski <zueski@gmail.com>"]
edition = "2018"
include = ["src/*.rs", "Cargo.toml"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4"
dbus = "0.7.1"
